---
output:
  reprex::reprex_document:
    advertise: false
    html_preview: false
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

```{r results='asis', echo = FALSE, eval = TRUE}
d <- read.dcf("DESCRIPTION")
```

```{r results="asis", echo = FALSE, eval = TRUE}
title <- d[colnames(d) == "Title"]
cat(c("# ", paste(trimws(strsplit(title, "\n")[[1]]), collapse = " ")))
```

<!-- badges: start -->
<!-- badges: end -->


```{r results="asis", echo = FALSE, eval = TRUE}
cat(d[colnames(d) == "Description"])
```


## Installation

You can install the released version of closure from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("closure")  # not yet released
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("randy3k/closure")
```
## Example

```{r}
library(closure)

Foo1 <- new_closure(list(
    counter = NULL,
    initialize = function(x) {
        counter <<- x
    },
    add = function(x) {
        counter <<- counter + x
        invisible(self)
    }
))
foo1 <- Foo1(1)
foo1$add(3)$counter

Foo2 <- toR6("Foo2", Foo1)
foo2 <- Foo2$new(1)
foo2$add(3)$counter
```

## Why?

First of all, closures are much faster.

```{r}
bench::mark(
    closure = foo1$add(3)$counter,
    R6 = foo2$add(3)$counter
)
```

And it is incredibly easier to make things wrong.

```{r}
g <- function(k) {
    function(x) {
        x^k
    }
}
m <- 2
h1 <- g(2)
h2 <- g(m)
m <- 3
identical(h1(2), h2(2))
```
See also, [advanced-R](https://adv-r.hadley.nz/function-factories.html#forcing-evaluation).


```{r}

```
